### ISSUE TITLE
Error: Cannot find module './utils/uuid'

### ISSUE THREAD

**Issue by flipphillips** [Jason-Rev/vscode-spell-checker#136]
I'm slowly regressing this as I type this, but in *vscode-insider* I'm seeing this error on launch:

> The Code Spell Checker server crashed 5 times in the last 3 minutes. The server will not be restarted.

 ```
Error: Cannot find module './utils/uuid'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/flip/.vscode-insiders/extensions/streetsidesoftware.code-spell-checker-1.4.0/server/node_modules/vscode-languageserver/lib/main.js:30:14)
    at Object.<anonymous> (/Users/flip/.vscode-insiders/extensions/streetsidesoftware.code-spell-checker-1.4.0/server/node_modules/vscode-languageserver/lib/main.js:691:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
[Info  - 10:52:15] Connection to server got closed. Server will restart.
module.js:472
    throw err;
    ^
```

This could very well be pilot error. I've just migrated to trying out the insider version on this machine (macOS) after quite a while of using the stable release.

Thus- just throwing this up here on the off chance anyone else is seeing this, will dutifully close/remove if I can figure out *why* it's happening.

It is a 'clean'  install of the app, I've removed the .vscode-insider directory @ my home.

**Comment by Jason3S** [comment]
Thank you.  I'll take a look.

**Comment by Jason3S** [comment]
I cannot reproduce this error.

Two questions: What version of insider and what version of the spell checker is loaded?

![image](https://user-images.githubusercontent.com/3740137/30606263-65cdd3b0-9d71-11e7-83bb-92cc69a69ddc.png)

![image](https://user-images.githubusercontent.com/3740137/30606291-8c10037c-9d71-11e7-9473-b554ff074922.png)

**Comment by flipphillips** [comment]
Same versions- however- a remove and reinstall of CSC seems to have fixed everything. I'm sorry for the false alarm.

**Comment by flipphillips** [comment]
The best bugs are those you don't need to fix, I always say.
