### ISSUE TITLE
Request textDocument/codeAction failed with message: Cannot find module '../encodings'

### ISSUE THREAD

**Issue by lmk123** [Jason-Rev/vscode-spell-checker#159]
It shows errors when I open any file:

```
[Error - 21:57:28] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Cannot find module '../encodings'
  Code: -32603 
{ Error: Cannot find module '../encodings'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.getCodec (/Users/xxx/.vscode/extensions/streetsidesoftware.code-spell-checker-1.5.1/server/node_modules/iconv-lite/lib/index.js:65:27)
    at Object.getDecoder (/Users/xxx/.vscode/extensions/streetsidesoftware.code-spell-checker-1.5.1/server/node_modules/iconv-lite/lib/index.js:122:23)
    at Object.decodeStream (/Users/xxx/.vscode/extensions/streetsidesoftware.code-spell-checker-1.5.1/server/node_modules/iconv-lite/lib/streams.js:16:49)
    at textFileStreamRx (/Users/xxx/.vscode/extensions/streetsidesoftware.code-spell-checker-1.5.1/server/node_modules/cspell-lib/dist/file/fileReader.js:21:22)
    at Object.lineReaderRx [as lineReader] (/Users/xxx/.vscode/extensions/streetsidesoftware.code-spell-checker-1.5.1/server/node_modules/cspell-lib/dist/file/fileReader.js:11:29)
    at Object.loadWordsRx (/Users/xxx/.vscode/extensions/streetsidesoftware.code-spell-checker-1.5.1/server/node_modules/cspell/dist/wordListHelper.js:10:25) code: 'MODULE_NOT_FOUND' }
```

Other infos maybe help:
  macOS: 10.13.1
  VS Code version: 1.18.1

Is this relate to https://github.com/ashtuchkin/iconv-lite/issues/118?

**Comment by Jason3S** [comment]
Wow, thank you. Yes, they seem to be related. Does restarting vscode work? It might be necessary to kill any Code Helpers that might still be open.

I use iconv, so it is very likely related.

**Comment by lmk123** [comment]
Strange... I reinstall code-spell-checker and restart VS Code, now it works properly.

**Comment by Jason3S** [comment]
That is basically what the other issue said.

Glad it is working for you.
