### ISSUE TITLE
Failed to start

### ISSUE THREAD

**Issue by rbenson** [Jason-Rev/vscode-spell-checker#189]
I loaded this on a new install of VSCode, and the following errors are thrown

```
Error: spawn C:\Program Files (x86)\Microsoft VS Code\Code.exe ENOENT
	at exports._errnoException (util.js:1050:11)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
	at onErrorNT (internal/child_process.js:367:16)
	at _combinedTickCallback (internal/process/next_tick.js:80:11)
	at process._tickCallback (internal/process/next_tick.js:104:9)
```

Do I have to start VSCode as an admin?

**Comment by Jason3S** [comment]
@rbenson thank you. I have never see this before. You do not need to run this as admin.

This is a VS Code error. Can you try uninstalling and re-installing the extension?

**Comment by rbenson** [comment]
Sorry life got crazy, Reinstalling fixed the  issue
