### ISSUE TITLE
Server crashes on Ubuntu

### ISSUE THREAD

**Issue by vmarkovtsev** [Jason-Rev/vscode-spell-checker#207]
vscode version: 1.21.1 (`79b44aa704ce542d8ca4a3cc44cfca566e7720f1`)
checker version: installed it today from the Marketplace
OS: Ubuntu 16.04 x64

The extension does not start, I see

![image](https://user-images.githubusercontent.com/2793551/38612273-7df7c97c-3d86-11e8-95ad-a5dfab399acb.png)

**Comment by rieznik** [comment]
@Jason3S Have the same issue here. Re-installed extension few times. Didn't help :disappointed: 
VSCode version: 1.22.2
Ubuntu 18.04
Here what I have in the VSCode output:
```
/home/kate/.vscode/extensions/streetsidesoftware.code-spell-checker-1.6.9/server/node_modules/configstore-fork/index.js:49
			throw err;
			^

Error: EACCES: permission denied, open '/home/kate/.config/configstore/cspell.json'
You don't have access to this file.

    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:491:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:505:29)
    at Configstore.get all [as all] (/home/kate/.vscode/extensions/streetsidesoftware.code-spell-checker-1.6.9/server/node_modules/configstore-fork/index.js:31:25)
    at Object.getGlobalSettings (/home/kate/.vscode/extensions/streetsidesoftware.code-spell-checker-1.6.9/server/node_modules/cspell/dist/Settings/CSpellSettingsServer.js:177:93)
    at Object.<anonymous> (/home/kate/.vscode/extensions/streetsidesoftware.code-spell-checker-1.6.9/server/src/server.js:28:102)
    at Object.<anonymous> (/home/kate/.vscode/extensions/streetsidesoftware.code-spell-checker-1.6.9/server/src/server.js:261:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
[Error - 7:22:34 PM] Connection to server got closed. Server will not be restarted.
```
.config/configstore folder has only root permissions
Hope it will help fixing it. I like this extension :blush:

**Comment by Jason3S** [comment]
@rieznik and @vmarkovtsev,

I believe this is now fixed. Can you please verify?

**Comment by vmarkovtsev** [comment]
@Jason3S It works, thanks a lot.

BTW, I have noticed that the extension reports many normal identifiers as out of vocabulary. My research team has just finished the paper about splitting 40 million identifiers collected from GitHub using deep learning. There are the trained model and the dataset coming soon. I think it should help with the spell checking... Does it sound interesting?

[bidirectional-lstm-model.pdf](https://github.com/Jason-Rev/vscode-spell-checker/files/1968927/bidirectional-lstm-model.pdf)

**Comment by Jason3S** [comment]
Thank you.  I'll read it!

**Comment by Jason3S** [comment]
If you have a dataset, it could be very useful. Splitting identifiers is hard.

**Comment by vmarkovtsev** [comment]
Here is the unofficial dataset - not published properly yet: https://yadi.sk/d/16K6y2X13UoyNp

**Comment by rieznik** [comment]
@Jason3S thank you, I made it work the other way. Had similar issue with other stuff.

**Comment by Jason3S** [comment]
Closing this as fixed.
