### ISSUE TITLE
Extension cannot start, crashes immediately

### ISSUE THREAD

**Issue by Kafkalasch** [Jason-Rev/vscode-spell-checker#230]
Hello,

i am using the latest version of Code Spell Checker (1.6.10) but it crashes always immediately after loading with the following message:

```
module.js:472
    throw err;
    ^

Error: Cannot find module './scalar'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (c:\Users\mh\.vscode\extensions\streetsidesoftware.code-spell-checker-1.6.10\server\node_modules\rxjs\internal\observable\of.js:6:16)
    at Object.<anonymous> (c:\Users\mh\.vscode\extensions\streetsidesoftware.code-spell-checker-1.6.10\server\node_modules\rxjs\internal\observable\of.js:30:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
[Info  - 09:49:27] Connection to server got closed. Server will restart.
```

this message is repeated a few times after vs code stops restarting the extension:
```
The Code Spell Checker server crashed 5 times in the last 3 minutes. The server will not be restarted.
```

**Comment by Kafkalasch** [comment]
Oh, I thought I had already tried that. Never mind, that worked. Thanks!
