### ISSUE TITLE
The Code Spell Checker server crasshed 5 times in the last 3 minutes.

### ISSUE THREAD

**Issue by miguel199** [Jason-Rev/vscode-spell-checker#233]
Dear Spell Checker team,
I'm having issues with this extension in a new Windows 10 machine.  I'm running version 1.6.10 with the following environment:

Visual Studio Code:
Version 1.24.1
Commit 24f62626b222e9a8313213fb64b10d741a326288
Date 2018-06-13T17:51:32.889Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

I have tried to reinstall the extension, but the problem persists.
The following is the error message on my terminal:

module.js:472
    throw err;
    ^

Error: Cannot find module './lib'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (c:\Users\pmhe007\.vscode\extensions\streetsidesoftware.code-spell-checker-1.6.10\server\node_modules\cspell-trie\dist\index.js:6:10)
    at Object.<anonymous> (c:\Users\pmhe007\.vscode\extensions\streetsidesoftware.code-spell-checker-1.6.10\server\node_modules\cspell-trie\dist\index.js:8:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
[Info  - 8:18:08 AM] Connection to server got closed. Server will restart.
module.js:472
    throw err;
    ^

Please let me know if you require more details.
Thanks

**Comment by Jason3S** [comment]
Thank you. I'll see if I can reproduce this issue.

**Comment by Jason3S** [comment]
Would you please try the following (sometimes things get stuck when VS Code is upgraded):

1. Uninstall the extension
2. Quit ALL copies of VS Code.
3. Ensure VS Code or (Code Helper) is not running in the background (kill it if it is)
4. Restart VS Code (only one copy)
5.  Install the extension

**Comment by miguel199** [comment]
Hi Jason, Thanks! Your suggestion works. It seems that it doesn't work if the uninstall and reinstall are performed in the same VS Code session, but after closing VS Code, the problem was fixed.
On the other hand, I'm not familiar with Node. I have applied a clean installation of VS Code on my machine. How can I make an update to 8.0?
