### ISSUE TITLE
Error: Cannot find module './util/toSubscriber'

### ISSUE THREAD

**Issue by RogueToad** [Jason-Rev/vscode-spell-checker#234]
Upon initialisation, "The Code Spell Checker server crashed 5 times in the last 3 minutes. The server will not be restarted" appears and the error log says:

`Error: Cannot find module './util/toSubscriber'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/chuckles/.vscode/extensions/streetsidesoftware.code-spell-checker-1.6.10/server/node_modules/rxjs/internal/Observable.js:3:22)
    at Object.<anonymous> (/home/chuckles/.vscode/extensions/streetsidesoftware.code-spell-checker-1.6.10/server/node_modules/rxjs/internal/Observable.js:299:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
[Error - 12:47:48] Connection to server got closed. Server will not be restarted.`

I'm running manjaro linux, but it works on my other machine so it may be my fault, I'm not sure. This is after a fresh install.

**Comment by Jason3S** [comment]
Thank you.

There seems to be an issue with VS Code on some installs. VS Code doesn't seem to correctly restart after an extension is added/updated.
