### ISSUE TITLE
Cannot find module 'vscode-languageserver'

### ISSUE THREAD

**Issue by RedTailBullet** [Jason-Rev/vscode-spell-checker#255]
So I am using the `1.6.10` version of the extension but when I start code, it throws this error multiple times. I tried installing `vscode-languageserver` using `npm -i -g vscode-languageserver` but it doesn't seems to work. I also tried to uninstall and reinstall the extension. None of the above solutions works.

I am running the Linux version of vscode. And on my other windows machine, everything is alright.

Here is the log:
```
Error: Cannot find module 'vscode-languageserver'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/scott/.vscode-oss/extensions/streetsidesoftware.code-spell-checker-1.6.10/server/src/server.js:4:33)
    at Object.<anonymous> (/home/scott/.vscode-oss/extensions/streetsidesoftware.code-spell-checker-1.6.10/server/src/server.js:246:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
[Info  - 17:54:26] Connection to server got closed. Server will restart.
module.js:472
    throw err;
    ^

Error: Cannot find module 'vscode-languageserver'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/scott/.vscode-oss/extensions/streetsidesoftware.code-spell-checker-1.6.10/server/src/server.js:4:33)
    at Object.<anonymous> (/home/scott/.vscode-oss/extensions/streetsidesoftware.code-spell-checker-1.6.10/server/src/server.js:246:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
[Error - 17:54:26] Connection to server got closed. Server will not be restarted.
```

**Comment by Jason3S** [comment]
Hello Scott,

This can happen when VS Code gets updated or the install didn't go as expected.

Things to try:
1. Restart VS Code -- make sure any `Code Helper` processes are gone before starting.
1. Uninstall the extension and install it again.

I hope this helps.

**Comment by RedTailBullet** [comment]
Hi Jason.

It worked! Thank you so much!

**Comment by cdyson37** [comment]
Same problem. Uninstall from the GUI didn't help; `rm -rf` the extension did though!

**Comment by vinothpandian** [comment]
> Same problem. Uninstall from the GUI didn't help; `rm -rf` the extension did though!
Thanks! It helped.

In Linux, use the following command

`rm -rf $HOME/.vscode/extensions/streetsidesoftware.code-spell-checker-*`

**Comment by stephenmathieson** [comment]
@vinothpandian thank you, `rm -rf`ing the extension and re-installing it from the UI worked perfectly for me.
