### ISSUE TITLE
Extension not working

### ISSUE THREAD

**Issue by Viking1983** [Jason-Rev/vscode-spell-checker#42]
Hi,
after update spell checker when I exrcute VSCode i see this bug:
Error: Cannot find module 'genSequence'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/*******/.vscode/extensions/streetsidesoftware.code-spell-checker-0.13.0/server/src/util/text.js:6:23)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
[Info  - 10:13:44] Connection to server got closed. Server will restart.
The Code Spell Checker server crashed 5 times in the last 3 minutes. The server will not be restarted.
VScode: 1.8.1
OS: Xubuntu 16.04.1
Extension version: 0.13.0

**Comment by Jason3S** [comment]
Thank you.  I'll fix that right away.

**Comment by Jason3S** [comment]
I have published a fix.  Please install 0.13.1.

**Comment by Viking1983** [comment]
It's working! Thanks!
