### ISSUE TITLE
Activating extension `streetsidesoftware.code-spell-checker` failed: Cannot find module 'vscode-languageclient'

### ISSUE THREAD

**Issue by laggingreflex** [Jason-Rev/vscode-spell-checker#68]
Getting this error in devtools on latest build (1.9.1):
```
Activating extension `streetsidesoftware.code-spell-checker` failed: Cannot find module 'vscode-languageclient'.t.$localShowMessage @ mainThreadExtensionService.ts:110
extensionHost.ts:282[Extension Host] Activating extension `streetsidesoftware.code-spell-checker` failed: Cannot find module 'vscode-languageclient'.d.logExtensionHostMessage @ extensionHost.ts:282
extensionHost.ts:282[Extension Host] Activating extension `streetsidesoftware.code-spell-checker` failed:  Cannot find module 'vscode-languageclient'd.logExtensionHostMessage @ extensionHost.ts:282
extensionHost.ts:282[Extension Host] Here is the error stack:  Error: Cannot find module 'vscode-languageclient'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Function.V.o._load (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:14:30928)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\x\.vscode\extensions\streetsidesoftware.code-spell-checker-0.14.6\out\src\extension.js:8:33)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Function.V.o._load (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:14:30928)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Function.s [as __$__nodeRequire] (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\loader.js:4:24952)
    at p (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:15:47)
```

**Comment by Jason3S** [comment]
Thank you.  I'll take a look.

**Comment by Jason3S** [comment]
Looks like you have a very old version of the extension (0.14.6).  Please update to 0.17.2.

**Comment by laggingreflex** [comment]
You're right! (and a wizard apparently :)

**Comment by laggingreflex** [comment]
The extensions panel isn't showing me the "update" button. Not sure if it's a bug in vscode.. I did remember updating a different plugin a few days ago though. 

![image](https://cloud.githubusercontent.com/assets/2523987/22862409/c9a5b986-f153-11e6-9ffc-f8f4ea6a54f5.png)

**Comment by Jason3S** [comment]
It is weird that way.  If you search for "spell" in the extension library, it should show you the option to upgrade.  If it does not, you can always just uninstall and install again.
