### ISSUE TITLE
Problem with word.tolowercase

### ISSUE THREAD

**Issue by jose-a-sa** [Jason-Rev/vscode-spell-checker#86]
The spellchecker doenst work at all. Always receiving the error:
```
[Error - 19:19:08] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: word.toLowerCase is not a function
  Code: -32603 
TypeError: word.toLowerCase is not a function
    at gensequence_1.genSequence.map.word (C:\Users\Jose\.vscode\extensions\streetsidesoftware.code-spell-checker-1.0.2\server\node_modules\cspell\dist\SpellingDictionary\SpellingDictionary.js:25:80)
    at fn (C:\Users\Jose\.vscode\extensions\streetsidesoftware.code-spell-checker-1.0.2\server\node_modules\gensequence\lib\src\GenSequence.js:118:19)
    at next (<anonymous>)
    at new Set (native)
    at Object.createSpellingDictionary (C:\Users\Jose\.vscode\extensions\streetsidesoftware.code-spell-checker-1.0.2\server\node_modules\cspell\dist\SpellingDictionary\SpellingDictionary.js:25:19)
    at Object.getDictionary (C:\Users\Jose\.vscode\extensions\streetsidesoftware.code-spell-checker-1.0.2\server\node_modules\cspell\dist\SpellingDictionary\Dictionaries.js:16:69)
    at Object.validateText (C:\Users\Jose\.vscode\extensions\streetsidesoftware.code-spell-checker-1.0.2\server\node_modules\cspell\dist\validator.js:8:29)
    at validateTextDocumentAsync (C:\Users\Jose\.vscode\extensions\streetsidesoftware.code-spell-checker-1.0.2\server\src\validator.js:16:47)
    at Object.validateTextDocument (C:\Users\Jose\.vscode\extensions\streetsidesoftware.code-spell-checker-1.0.2\server\src\validator.js:10:12)
    at SafeSubscriber.validateTextDocument [as _next] (C:\Users\Jose\.vscode\extensions\streetsidesoftware.code-spell-checker-1.0.2\server\src\server.js:127:23)
```

**Comment by Jason3S** [comment]
Wow. That is odd.  Thank you.

What version of VS Code are you running?
Do you know which version of the spell checker you have installed?

**Comment by Jason3S** [comment]
Did you customize it at all?

It is blowing up on adding custom words into a dictionary.

**Comment by jose-a-sa** [comment]
I found out the problem. It's the command `cSpell.addWordToDictionarySilent`. When assigning a key shortcut to this command, when I do the assigned key combination when selecting/hovering some word it adds `{}` to the `"words"` variable inside the `cSpell.json` file.

**Comment by Jason-Rev** [comment]
Nice catch.

There are a couple of things I can do to keep it from crashing.

**Comment by Jason3S** [comment]
The next time I update the cspell library, this issue should be fixed.

**Comment by Jason3S** [comment]
This should now be fixed.
