### ISSUE TITLE
Cannot read property 'document' of undefined when multiple groups are open

### ISSUE THREAD

**Issue by CaselIT** [Jason-Rev/vscode-spell-checker#88]
Steps to reproduce for me: 
- open vscode on a folder, 
- open files on two editor group, 
- select the file on the right editor group, 
- click on the cSpell area on the status bar

The stack trace:
```
messageService.ts:126 Unable to open 'Spell Checker Info': Cannot read property 'document' of undefined.: Error: Unable to open 'Spell Checker Info': Cannot read property 'document' of undefined.
    at t.doHandleSetInputError (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29:367915)
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29:367521
    at Object.v [as _notify] (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:50893)
    at Object.enter (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:54394)
    at _run (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:55715)
    at _error (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:55232)
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:64923
    at done (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:56274)
    at Object.v [as _notify] (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:51066)
    at Object.enter (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:54394)
	e.doShow @ messageService.ts:126
	e.show @ messageService.ts:105
	t.doHandleSetInputError @ editorPart.ts:525
	(anonymous function) @ editorPart.ts:505
	v @ winjs.base.raw.js:1209
	enter @ winjs.base.raw.js:901
	_run @ winjs.base.raw.js:1068
	_error @ winjs.base.raw.js:1041
	(anonymous function) @ async.ts:360
	done @ winjs.base.raw.js:1378
	v @ winjs.base.raw.js:1224
	enter @ winjs.base.raw.js:901
	_run @ winjs.base.raw.js:1068
	_chainedError @ winjs.base.raw.js:1031
	n @ winjs.base.raw.js:736
	then @ winjs.base.raw.js:1436
	enter @ winjs.base.raw.js:747
	_run @ winjs.base.raw.js:1068
	_setCompleteValue @ winjs.base.raw.js:1052
	v @ winjs.base.raw.js:1209
	enter @ winjs.base.raw.js:901
	_run @ winjs.base.raw.js:1068
	_error @ winjs.base.raw.js:1041
	e.resolveErr @ ipcRemoteCom.ts:111
	f @ ipcRemoteCom.ts:203
	_combinedTickCallback @ internal/process/next_tick.js:67
	_tickCallback @ internal/process/next_tick.js:98
index.js:36 [uncaught exception]: TypeError: Cannot read property 'document' of undefined
	onError @ index.js:36
	(anonymous function) @ index.js:105
	emitOne @ events.js:96
	emit @ events.js:188
	window.onerror @ C:\Program Files (x86)\Microsoft VS Code\resources\electron.asar\renderer\init.js:120
	i.globals.onerror @ errorTelemetry.ts:64
index.js:39 TypeError: Cannot read property 'document' of undefined
    at CSpellInfoTextDocumentContentProvider.createInfoHtml (C:\Users\Federico\.vscode\extensions\streetsidesoftware.code-spell-checker-1.0.2\out\src\cSpellInfo.js:44:36)
    at CSpellInfoTextDocumentContentProvider.provideTextDocumentContent (C:\Users\Federico\.vscode\extensions\streetsidesoftware.code-spell-checker-1.0.2\out\src\cSpellInfo.js:35:25)
    at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:307559
    at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:58869
    at new n.Class.derive._oncancel (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:54918)
    at Object.p [as asWinJsPromise] (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:58832)
    at t.$provideTextDocumentContent (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:307523)
    at t.e.handle (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:277319)
    at s (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:135077)
    at h (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:135754)onError @ index.js:39(anonymous function) @ index.js:105emitOne @ events.js:96emit @ events.js:188window.onerror @ C:\Program Files (x86)\Microsoft VS Code\resources\electron.asar\renderer\init.js:120i.globals.onerror @ errorTelemetry.ts:64
ipcRemoteCom.ts:198 Uncaught TypeError: Cannot read property 'document' of undefined
	f @ ipcRemoteCom.ts:198
	_combinedTickCallback @ internal/process/next_tick.js:67
	_tickCallback @ internal/process/next_tick.js:98
```

**Comment by Jason3S** [comment]
I do not think this is related to #78. It is a bug in how the preview pane handles focus changes between editors.

**Comment by CaselIT** [comment]
I was just guessing since #78 is quite mysterious :)

Let me know if I you need more information.
I forgot to add the vscode info on the OP.

- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.16179
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|jupyter|donjayamanne|1.1.1|
|python|donjayamanne|0.6.3|
|tslint|eg2|0.12.0|
|docthis|joelday|0.4.3|
|latexcompile|mathiasfrohlich|0.7.0|
|latex|ms-vscode|0.1.3|
|typescript-javascript-grammar|ms-vscode|0.0.18|
|code-spell-checker|streetsidesoftware|1.0.2|;

**Comment by Jason3S** [comment]
Thank you.  I have an idea what is causing this.  It is related to how VS Code changes focus between editor panes.

**Comment by Jason3S** [comment]
Please update the extension, this issue should be fixed.

**Comment by CaselIT** [comment]
Thank you. That was fast 👍
